# Generated by Django 5.2.9 on 2025-12-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('MATEMATICAS', 'Matemáticas'), ('CIENCIAS', 'Ciencias'), ('INGENIERIA', 'Ingeniería'), ('IDIOMAS', 'Idiomas'), ('HUMANIDADES', 'Humanidades'), ('NEGOCIOS', 'Negocios'), ('ARTE', 'Arte y Diseño'), ('TECNOLOGIA', 'Tecnología')], default='MATEMATICAS', max_length=50),
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('BASICO', 'Básico'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='BASICO', max_length=20),
        ),
    ]
