# Generated by Django 5.2.9 on 2025-12-10 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_categoria_curso_nivel'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='🏆', max_length=10)),
                ('tipo', models.CharField(choices=[('CURSO', 'Completar Curso'), ('EXAMEN', 'Aprobar Examen'), ('RACHA', 'Días Consecutivos'), ('PUNTOS', 'Acumular Puntos'), ('ESPECIAL', 'Logro Especial')], max_length=20)),
                ('puntos_recompensa', models.IntegerField(default=0)),
                ('condicion_valor', models.IntegerField(help_text='Valor necesario para desbloquear (ej: 100 puntos, 7 días)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'db_table': 'logro',
            },
        ),
        migrations.CreateModel(
            name='ActividadEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('VER_RECURSO', 'Ver recurso'), ('COMPLETAR_RECURSO', 'Completar recurso'), ('INICIAR_EXAMEN', 'Iniciar examen'), ('COMPLETAR_EXAMEN', 'Completar examen'), ('INSCRIPCION_CURSO', 'Inscripción a curso')], max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('puntos_ganados', models.IntegerField(default=0)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='usuarios.estudiante')),
            ],
            options={
                'verbose_name': 'Actividad de Estudiante',
                'verbose_name_plural': 'Actividades de Estudiantes',
                'db_table': 'actividad_estudiante',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LogroEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenido', models.DateTimeField(auto_now_add=True)),
                ('progreso_actual', models.IntegerField(default=0)),
                ('desbloqueado', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='usuarios.estudiante')),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.logro')),
            ],
            options={
                'verbose_name': 'Logro de Estudiante',
                'verbose_name_plural': 'Logros de Estudiantes',
                'db_table': 'logro_estudiante',
                'unique_together': {('estudiante', 'logro')},
            },
        ),
    ]
