# Generated by Django 5.2.9 on 2025-12-10 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_logro_actividadestudiante_logroestudiante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(choices=[('PREGUNTA', 'Pregunta'), ('DISCUSION', 'Discusión'), ('AYUDA', 'Ayuda'), ('ANUNCIO', 'Anuncio')], default='PREGUNTA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('resuelto', models.BooleanField(default=False)),
                ('vistas', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas_foro', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temas_foro', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Tema de Foro',
                'verbose_name_plural': 'Temas de Foro',
                'db_table': 'tema_foro',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('es_solucion', models.BooleanField(default=False)),
                ('votos', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_foro', to=settings.AUTH_USER_MODEL)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='cursos.temaforo')),
            ],
            options={
                'verbose_name': 'Respuesta de Foro',
                'verbose_name_plural': 'Respuestas de Foro',
                'db_table': 'respuesta_foro',
                'ordering': ['-es_solucion', '-votos', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='VotoRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('UP', 'Voto Positivo'), ('DOWN', 'Voto Negativo')], max_length=4)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_detalle', to='cursos.respuestaforo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto de Respuesta',
                'verbose_name_plural': 'Votos de Respuestas',
                'db_table': 'voto_respuesta',
                'unique_together': {('respuesta', 'usuario')},
            },
        ),
    ]
