# Generated by Django 5.2.9 on 2025-12-11 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_temaforo_respuestaforo_votorespuesta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('ENCUESTA', 'Encuesta'), ('FEEDBACK', 'Feedback'), ('EVALUACION', 'Evaluación')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('anonimo', models.BooleanField(default=False)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_creados', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'db_table': 'formulario',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField()),
                ('tipo', models.CharField(choices=[('TEXTO_CORTO', 'Texto Corto'), ('TEXTO_LARGO', 'Texto Largo'), ('OPCION_MULTIPLE', 'Opción Múltiple'), ('CASILLAS', 'Casillas de Verificación'), ('ESCALA', 'Escala (1-5)'), ('SI_NO', 'Sí/No')], max_length=20)),
                ('opciones', models.JSONField(blank=True, null=True)),
                ('requerida', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='cursos.formulario')),
            ],
            options={
                'verbose_name': 'Pregunta de Formulario',
                'verbose_name_plural': 'Preguntas de Formulario',
                'db_table': 'pregunta_formulario',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RecursoComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('DOCUMENTO', 'Documento'), ('VIDEO', 'Video'), ('ENLACE', 'Enlace'), ('CODIGO', 'Código'), ('PRESENTACION', 'Presentación')], max_length=20)),
                ('archivo_url', models.URLField(blank=True, null=True)),
                ('contenido_texto', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('descargas', models.IntegerField(default=0)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('aprobado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_compartidos', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos_comunidad', to='cursos.curso')),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos_comunidad', to='cursos.modulo')),
            ],
            options={
                'verbose_name': 'Recurso de Comunidad',
                'verbose_name_plural': 'Recursos de Comunidad',
                'db_table': 'recurso_comunidad',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DescargaRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_descargas', to='cursos.recursocomunidad')),
            ],
            options={
                'verbose_name': 'Descarga de Recurso',
                'verbose_name_plural': 'Descargas de Recursos',
                'db_table': 'descarga_recurso',
            },
        ),
        migrations.CreateModel(
            name='RespuestaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='cursos.formulario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta de Formulario',
                'verbose_name_plural': 'Respuestas de Formularios',
                'db_table': 'respuesta_formulario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField(blank=True)),
                ('respuesta_opcion', models.CharField(blank=True, max_length=255)),
                ('respuesta_multiple', models.JSONField(blank=True, null=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.preguntaformulario')),
                ('respuesta_formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cursos.respuestaformulario')),
            ],
            options={
                'verbose_name': 'Detalle de Respuesta',
                'verbose_name_plural': 'Detalles de Respuestas',
                'db_table': 'detalle_respuesta',
            },
        ),
        migrations.CreateModel(
            name='CalificacionRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='cursos.recursocomunidad')),
            ],
            options={
                'verbose_name': 'Calificación de Recurso',
                'verbose_name_plural': 'Calificaciones de Recursos',
                'db_table': 'calificacion_recurso',
                'unique_together': {('recurso', 'usuario')},
            },
        ),
    ]
