# Generated by Django 5.2.9 on 2025-12-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('cursos', '0005_formulario_preguntaformulario_recursocomunidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_examen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='hora_examen',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProximaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('EXAMEN', 'Examen'), ('QUIZ', 'Quiz'), ('TAREA', 'Tarea'), ('ESTUDIO', 'Estudio'), ('TUTORIA', 'Tutoría'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('FECHA_EXAMEN', 'Fecha de examen')], default='MANUAL', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proximas_actividades', to='cursos.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proximas_actividades', to='usuarios.estudiante')),
            ],
            options={
                'verbose_name': 'Próxima actividad',
                'verbose_name_plural': 'Próximas actividades',
                'db_table': 'proxima_actividad',
                'ordering': ['fecha', 'hora', 'id'],
            },
        ),
    ]

