# Generated by Django 5.2.9 on 2025-12-15 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_inscripcion_fecha_examen_proximaactividad'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorPerfil',
            fields=[
                ('creador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tutor_perfil', serialize=False, to='usuarios.creador')),
                ('materias', models.CharField(blank=True, default='', max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('tarifa_30_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tarifa_60_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de tutor',
                'verbose_name_plural': 'Perfiles de tutor',
                'db_table': 'tutor_perfil',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('alert', 'Alert')], default='info', max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_minutos', models.PositiveIntegerField(default=30)),
                ('tema', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('ACEPTADA', 'Aceptada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='SOLICITADA', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorias', to='cursos.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorias', to='usuarios.estudiante')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorias', to='usuarios.creador')),
            ],
            options={
                'verbose_name': 'Tutoría',
                'verbose_name_plural': 'Tutorías',
                'db_table': 'tutoria',
                'ordering': ['-creado_en'],
            },
        ),
    ]
