# Generated by Django 5.2.9 on 2025-12-15 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_tutorperfil_notificacion_tutoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recursocomunidad',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='recursos_comunidad/'),
        ),
        migrations.CreateModel(
            name='FormularioEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('materia', models.CharField(blank=True, default='General', max_length=200)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='formularios_estudio/')),
                ('archivo_url', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_estudio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formulario de estudio',
                'verbose_name_plural': 'Formularios de estudio',
                'db_table': 'formulario_estudio',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
