# Generated by Django 4.2.26 on 2025-12-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='creador',
            name='biografia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creador',
            name='tarifa_30_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='creador',
            name='tarifa_60_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tiempo_estudio_minutos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
